### ISSUE TITLE
Bits in prepare statement null bitmaps are never reset to zero once they've been set to one

### ISSUE THREAD

**Issue by jrboelens** [ziutek/mymysql#104]
The initialization of a prepare statement's bitmap takes place after reading the result of the **PREPARE** call.  At this point, all bytes in the bitmap are zero. 

During the **EXECUTE** the following code block is executed.  In this block, each parameter deemed to have a zero length has its bit flipped in the appropriate byte in the bit map.

However, there is no code that flips the null bitmap bits back to zero on subsequent **EXECUTE** calls.

**In prepared.go:**
````go
for ii, param := range stmt.params {
	par_len := param.Len()
	pkt_len += par_len
	if par_len == 0 {
		null_byte := ii >> 3
		null_mask := byte(1) << uint(ii-(null_byte<<3))
		stmt.null_bitmap[null_byte] |= null_mask
	}
}
````
If you use a table where the first column is NULLable, insert a row with a NULL value, then insert a row with a real value, you will receive the following error:
````
MySQL Error Code: 1210 Message: Incorrect arguments to mysqld_stmt_execute (PC=0x40EE5D)
````

It is my understanding this is due to the fact that the null bitmap is indicating that the column should be null, but the value is still being placed in the binary packet.

I was able to fix this issue in two different ways.  

The first method is to simply flip all the bits back to zero for each parameter that doesn't have length.  In this version, you're having to touch every bit individually each time you **EXECUTE**

**In prepared go.**
````go
for ii, param := range stmt.params {
	par_len := param.Len()
	pkt_len += par_len
	null_byte := ii >> 3
	null_mask := byte(1) << uint(ii-(null_byte<<3))		
	if par_len == 0 {
	        stmt.null_bitmap[null_byte] |= null_mask
	} else {
	        stmt.null_bitmap[null_byte] &= ^null_mask
	}
}
````

The second method uses the fact that there are eight times fewer bytes than there are parameters (bits).  It simply clears all the bytes in the null bitmap before each **EXECUTE**.  This method also prevents the calculation of **null_byte** and **null_mask** for non NULL parameters.

**In prepared.go:**
````go
for i := 0; i < len(stmt.null_bitmap); i++ {
	stmt.null_bitmap[i] = 0
}

for ii, param := range stmt.params {
	par_len := param.Len()
	pkt_len += par_len
	if par_len == 0 {
		null_byte := ii >> 3
		null_mask := byte(1) << uint(ii-(null_byte<<3))
		stmt.null_bitmap[null_byte] |= null_mask
	}
}
````

**Comment by ziutek** [comment]
Thanks for very clear explanation. Fixed in last commit.

**Comment by jrboelens** [comment]
You're most welcome.  Thanks for quickly committing  the change.
