### ISSUE TITLE
Packet sequence error after a multi statement query has completed.

### ISSUE THREAD

**Issue by nomad-software** [ziutek/mymysql#105]
In the following code i am issuing a multi-statement query to drop and then create a database. This query executes successfully but all other queries after that fail with a packet sequence error.

``` sql
// Package.
package main

// Imports.
import "database/sql"
import "fmt"
import _ "github.com/ziutek/mymysql/godrv"

// Main entry point.
func main() {

    db, err := sql.Open("mymysql", "test/gary/")
    if err != nil {
        fmt.Println("Open;", err)
    }

    sql := "DROP SCHEMA IF EXISTS foo; CREATE SCHEMA IF NOT EXISTS foo;"
    _, err = db.Exec(sql)
    if err != nil {
        fmt.Println(sql, err)
    }

    sql = "USE DATABASE foo;"
    _, err = db.Exec(sql)
    if err != nil {
        fmt.Println(sql, err)
    }

    db.Close()
}
```

Output:

```
USE DATABASE foo; packet sequence error
```

**Comment by nomad-software** [comment]
This only seems to be an issue when using the standard go interface (`github.com/ziutek/mymysql/godrv`). If using the native engine this is not an issue.

**Comment by ziutek** [comment]
In such case server returns multiple results but database/sql reads only first one (it can't handle multiple results). This probably can be fixed in way that discards remaining results and return error.

**Comment by benji-vesterby** [comment]
I'm running into this issue with the native engine. Is this something that has been resolved?

**Comment by ziutek** [comment]
Ensure that you read all data from first result.

**Comment by benji-vesterby** [comment]
I've decided to use a different driver, and it's working. Thank you for the quick response.

**Comment by jackluo2012** [comment]
I also met, I don't know how to solve it?

**Comment by jackluo2012** [comment]
> Ensure that you read all data from first result.

Can you give a pseudo code, I don't know how to write？

**Comment by jackluo2012** [comment]
I fixed my code，the reason
`var db *mysql.DB //定义了全局的db

func init() {
     db, _ = MysqlConn.Get().(*mysql.DB) //封装的线程池里拿
}`
changed to
`func GetDB() *mysql.DB {
    return MysqlConn.Get().(*mysql.DB)
}`
Db cannot be attached to init
https://www.cnblogs.com/jackluo/p/10216138.html
