### ISSUE TITLE
Short Write error periodically

### ISSUE THREAD

**Issue by ready4god2513** [ziutek/mymysql#118]
Unfortunately I don't have exact steps to reproduce the error, but periodically my application will go into a fit of "short write" errors for all queries until the server is restarted.  I do know that the IO package returns a "short write" error if `a write accepted fewer bytes than requested but failed to return an explicit error.` which I believe can happen inside of io.Copy, which is found here - https://github.com/ziutek/mymysql/blob/b559dddd7e2a2ce596f2058bc399805102719eac/native/packet.go#L119 and https://github.com/ziutek/mymysql/blob/b559dddd7e2a2ce596f2058bc399805102719eac/native/packet.go#L140

My question, and I am not 100% sure that the driver causes the error, but I had thought that possibly you had come across that error before and knew something about it.  Any ideas?

**Comment by ready4god2513** [comment]
Anyone?

**Comment by peterkellyonline** [comment]
:+1: this is happening a lot
