### ISSUE TITLE
Not connecting when given a tcp: string

### ISSUE THREAD

**Issue by Eggbertx** [ziutek/mymysql#123]
I'm trying to connect to a MySQL server using a tcp connection instead of a UNIX socket. I can connect to the server just fine with the socket, but tcp connections are returning "driver: bad connection" errors.

```golang
sql.Open("mymysql", config.DBhost + "*" + config.DBname + "/"+config.DBusername+"/"+config.DBpassword)
```
so with config.DBhost set to unix:/var/run/mysqld/mysqld.sock, it connects just fine, but it set to tcp:127.0.0.1, it doesn't. Am I doing something wrong, or is this a known bug?
(sql.open refers to Go's built-in database/sql package)

**Comment by ziutek** [comment]
See for examples. Try add port number to URL:
tcp:127.0.0.1:3306*mydb/username/passw0rd

**Comment by Eggbertx** [comment]
Oh, that fixes it. Thank you
