### ISSUE TITLE
driver: bad connection error

### ISSUE THREAD

**Issue by HANAND1979** [ziutek/mymysql#126]
Hi,

We are using the below code to connect to CloudSQL. After deploying to AppEngine, we keep getting this error. **[driver: bad connection error]**

How do we get this working? We have tried using both options of connection strings. In both cases we get the same issue. Sharing unedited code so you can try replicating. 

package main

import (
	"database/sql"
	"fmt"
	"net/http"
	_ "github.com/ziutek/mymysql/godrv"
)

func init() {
	http.HandleFunc("/", connect_sql)
}

func connect_sql(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Attempting to connect to Google Cloud SQL...")
	db, err := sql.Open("mymysql", "cloudsql:myappmulti:myappmulti*demo/root/admin")
	//db, err := sql.Open("mymysql", "tcp:104.197.140.181:3306*demo/root/admin")
	if err != nil {
		fmt.Fprintf(w, err.Error())
	}
	defer db.Close()
	err = db.Ping()
	if err != nil {
		fmt.Fprintf(w, err.Error())
	}
	_, err = db.Exec(`insert into stocks (scripid,price) values('RAY',100)`)

	if err != nil {
		fmt.Fprintf(w, err.Error())
	} else {
		fmt.Fprintf(w, "Values inserted")
	}
}

**Comment by ziutek** [comment]
I blieve this should work:

  cloudsql:INSTANCE*DBNAME/USER/PASSWD

In case of appengine this causes that

  cloudsql.Dial(INSTANCE)

is called. See appengine/cloudsql package documentation for more info.

**Comment by HANAND1979** [comment]
Thank you. It is working. The issue wasn't with the driver per se. It was with how we combined Google AppEngine environment (Managed VM versus Standard) with Cloud SQL (First gen or Second Gen). We had used Standard AppEngine environment with 2nd Gen Cloud SQL and encountered a whole host of issues. Wish the GCP system itself prevents such a choice from being made. Thanks once again.
